site:
  title: Romme
  url: https://docs.playromme.com
content:
  sources: 
  - url: ./
    branches: HEAD
ui: 
  bundle:
    url: ./ui-bundle
    snapshot: true
urls:
  latest_version_segment_strategy: redirect:to 
  latest_version_segment: stable
asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki