name: server
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
    - 'server/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_PROJECT_PATH: server
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./server
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "16"
        - name: Install dependencies
          run: npm install
        - name: Run the tests
          run: npm test -- --coverage
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets. SONAR_TOKEN_SERVER }}
          with:
            projectBaseDir: server
        - uses: hadolint/hadolint-action@v1.6.0
          with:
            dockerfile: server/Dockerfile
        - uses: superfly/flyctl-actions@1.3
          with:
            args: "deploy"